### ISSUE TITLE
can not run this repo on one card 3090

### ISSUE THREAD

**Issue by dchenhe** [zhuhr213/HDRNet#2]
you mentioned the training and inference can run on one 3090 GPU card. But I tried it, there will be error about OOM(out of memory). Is there anything wrong?

**Comment by zhuhr213** [comment]
hello, @dchenhe 
sorry for the delayed fix. This is a funny bug caused by the "pad_to_max_length" in transformers, which was actually deprecated. I changed this option to "padding = max_length" so that there wouldn't be any warnings, but directly caused that it truly pad to max length, which was 512 by default. And finally it comes to the OOM error. We have fixed this problem in the newest release. Again, sorry for my delayed reply.

haoran
